In [2]:
import pandas as pd
import numpy as np

In [24]:
df1= pd.read_csv("exports/AIF 2025 Entrance Exam - April 5th.csv")
df2= pd.read_csv("exports/AIF 2025 Entrance Exam - April 6th.csv")
df3= pd.read_csv("exports/AIF 2025 Entrance Exam - April 7th.csv")
df4= pd.read_csv("exports/AIF 2025 Entrance Re Exam - April 8th.csv")
df5= pd.read_csv("exports/AIF 2025 Entrance Re Exam - April 9th.csv")
df6= pd.read_csv("exports/AIF 2025 Entrance Exam Sazience.csv")

In [25]:
df1.shape

(500, 7)

In [26]:
# concat dataframe
df= pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

In [27]:
df.head()

,Name,TOTAL SCORE,Unnamed: 2,SUBMITTED DATE,Violation Status,STATUS,Unnamed: 6
0,GAUTAM MANOJmg2671037@gmail.com,80/100,NaN,"April 05 , 2025 05:49 PM",Low,Passed,view submission
1,AADITYA RAJ PAUDELaadityapaudel834@gmail.com,76/100,NaN,"April 05 , 2025 09:28 AM",Low,Passed,view submission
2,MAUSAM GURUNGmausaam.gurung593@gmail.com,78/100,NaN,"April 05 , 2025 07:49 AM",Low,Passed,view submission
3,NAGENDRA CHAUDHARYnagendrachaudhary1999@gmail.com,90/100,NaN,"April 05 , 2025 07:51 AM",Low,Passed,view submission
4,DHARMENDRA SINGH CHAUDHARYcdharmendrasingh892@...,52/100,NaN,"April 05 , 2025 07:52 PM",Low,Failed,view submission

In [28]:
df.shape

(1856, 7)

In [29]:
# get date only
df['SUBMITTED DATE']= pd.to_datetime(df1['SUBMITTED DATE']).dt.date

/tmp/ipykernel_58103/1134121081.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['SUBMITTED DATE']= pd.to_datetime(df1['SUBMITTED DATE']).dt.date

In [30]:
df1.head()

,Name,TOTAL SCORE,Unnamed: 2,SUBMITTED DATE,Violation Status,STATUS,Unnamed: 6
0,GAUTAM MANOJmg2671037@gmail.com,80/100,NaN,"April 05 , 2025 05:49 PM",Low,Passed,view submission
1,AADITYA RAJ PAUDELaadityapaudel834@gmail.com,76/100,NaN,"April 05 , 2025 09:28 AM",Low,Passed,view submission
2,MAUSAM GURUNGmausaam.gurung593@gmail.com,78/100,NaN,"April 05 , 2025 07:49 AM",Low,Passed,view submission
3,NAGENDRA CHAUDHARYnagendrachaudhary1999@gmail.com,90/100,NaN,"April 05 , 2025 07:51 AM",Low,Passed,view submission
4,DHARMENDRA SINGH CHAUDHARYcdharmendrasingh892@...,52/100,NaN,"April 05 , 2025 07:52 PM",Low,Failed,view submission

In [31]:
df.drop(columns=['Violation Status', 'STATUS', 'Unnamed: 2', 'Unnamed: 6'], inplace=True)

In [32]:
df.head()

,Name,TOTAL SCORE,SUBMITTED DATE
0,GAUTAM MANOJmg2671037@gmail.com,80/100,2025-04-05
1,AADITYA RAJ PAUDELaadityapaudel834@gmail.com,76/100,2025-04-05
2,MAUSAM GURUNGmausaam.gurung593@gmail.com,78/100,2025-04-05
3,NAGENDRA CHAUDHARYnagendrachaudhary1999@gmail.com,90/100,2025-04-05
4,DHARMENDRA SINGH CHAUDHARYcdharmendrasingh892@...,52/100,2025-04-05

In [33]:
df["Email"] = df["Name"].str.extract(r'([a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,})')

# Extract name (uppercase part before email)
df["Name_clean"] = df["Name"].str.extract(r'([A-Z ]+)(?=[a-z0-9._%+-]+@)')

# Strip extra spaces
df["Name_clean"] = df["Name_clean"].str.strip()

In [34]:
df.head()

,Name,TOTAL SCORE,SUBMITTED DATE,Email,Name_clean
0,GAUTAM MANOJmg2671037@gmail.com,80/100,2025-04-05,mg2671037@gmail.com,GAUTAM MANOJ
1,AADITYA RAJ PAUDELaadityapaudel834@gmail.com,76/100,2025-04-05,aadityapaudel834@gmail.com,AADITYA RAJ PAUDEL
2,MAUSAM GURUNGmausaam.gurung593@gmail.com,78/100,2025-04-05,mausaam.gurung593@gmail.com,MAUSAM GURUNG
3,NAGENDRA CHAUDHARYnagendrachaudhary1999@gmail.com,90/100,2025-04-05,nagendrachaudhary1999@gmail.com,NAGENDRA CHAUDHARY
4,DHARMENDRA SINGH CHAUDHARYcdharmendrasingh892@...,52/100,2025-04-05,cdharmendrasingh892@gmail.com,DHARMENDRA SINGH CHAUDHARY

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df.shape

(86, 5)